### ISSUE TITLE
input datatype

### ISSUE THREAD

**Issue by iBM88** [Craigacp/MIToolbox#1]
The code gets to the following error while running MIToolbox on uint8 data types:
"Out of memory. Type HELP MEMORY for your options."

However it works well with double data type.

**Comment by Craigacp** [comment]
Yes, the C code expects all the inputs to be doubles, and it assumes that any input handed by Matlab will be a double (through an explicit cast). The Matlab wrappers probably should be modified to test the arrays and convert them to doubles first, though this will be slow if the user doesn't realise it's happening.

**Comment by edobez** [comment]
Hello, I have faced the same problem as @iBM88 had until I started looking for help online. 
I think this should be written in the README since it's quite an important thing.
Also there are some kinds of inputs which make MATLAB crash (at least in R2015a), for example when they are matrices instead of column vectors.

**Comment by Craigacp** [comment]
I'll work on the README at the weekend, it could do with a touch up.

What kind of inputs make it crash? Is this directly calling the mex functions or using the MATLAB wrappers?

**Comment by edobez** [comment]
Matrix inputs and uint8 vectors. It crashed calling the MATLAB wrapper `mi`.

**Comment by Craigacp** [comment]
So you called mi(X,Y) where X & Y were both matrices of uint8 values?

**Comment by edobez** [comment]
Yes, for example:
`I = imread('cameraman.tif');`
`mi(I,I)` --> crashes
`mi(I(:),(:))` --> crashes

**Comment by Craigacp** [comment]
Ok. I've added checks to the MATLAB wrappers so they reject inputs which aren't doubles. It should now throw an error message rather than crashing MATLAB.
